---
title: "Group_charact_exp2"
author: "Lisa Lemmens"
date: "February 19, 2019"
output: html_document
---
```{r}
library(readr)
library(data.table)
library(reshape2)
library(lme4)
library(readxl)
library("ggpubr")
library(segmented)
library(tidyverse)
library(ggplot2)

```

#Read in data
```{r}
demo_ASD <- read_csv("C:/Users/u0103239/Box Sync/PhD/Research/R/WP1/Experiment2/deelnemers_ASD.csv")
demo_TD <- read_csv("C:/Users/u0103239/Box Sync/PhD/Research/R/WP1/Experiment2/CONTROLEdeelnemers.csv")
demo_ASD <- select(demo_ASD, SubjectId,leeftijd, Geslacht, VIQ, PIQ,SRS_TOTAAL,IU,CBCL,SP)
demo_ASD <- filter(demo_ASD,!is.na(SubjectId))
demo_ASD$SubjectId = as.factor(demo_ASD$SubjectId)

demo_ASD$Group <- 'ASD'
demo_ASD <- filter(demo_ASD,!grepl("002",SubjectId))
demo_TD <- select(demo_TD, SubjectId,leeftijd, Geslacht, VIQ, PIQ,SRS_TOTAAL,IU,CBCL,SP)
demo_TD <- filter(demo_TD,!grepl("315",SubjectId),!grepl("316",SubjectId),!grepl("304",SubjectId),!grepl("322",SubjectId),!grepl("303",SubjectId),!grepl("321",SubjectId))
demo_TD$SubjectId = as.factor(demo_TD$SubjectId)
demo_TD$Group <- 'TD'
demo_TD$SP = as.integer(demo_TD$SP)


demo<-bind_rows(demo_ASD,demo_TD)
demo <- demo%>%
  mutate(FIQ=((PIQ + VIQ)/2))%>%
  rename(id=SubjectId)
demo$id = as.factor(demo$id)
demo$Group = factor(demo$Group)
```

#Summary table + t tests
```{r}
demo%>%
  group_by(Group)%>%
  summarise(N = n(),mean_age=mean(leeftijd), minimum_age=min(leeftijd), maximum_age = max(leeftijd), sd_age=sd(leeftijd), n_girls = sum(Geslacht))
demo%>% filter(leeftijd <11)%>%group_by(Group)%>%summarise(n=n())

mean(demo$leeftijd)
sd(demo$leeftijd)
min(demo$leeftijd)
max(demo$leeftijd)
t.test(demo$leeftijd ~ demo$Group)
t.test(demo$PIQ ~ demo$Group)
t.test(demo$VIQ ~ demo$Group)
t.test(demo$FIQ ~ demo$Group)
t.test(demo$CBCL ~ demo$Group)
t.test(demo$SRS_TOTAAL ~ demo$Group)
t.test(demo$SP ~ demo$Group)
```

#Boxplots
```{r}
ggplot(demo,aes(Group,leeftijd, color=Group)) + geom_boxplot() + geom_point() + theme_classic() + xlab("Group") + ylab("Age") + ggtitle("Age per group") 
ggplot(demo,aes(Group,PIQ, color=Group)) + geom_boxplot() + geom_point() + theme_classic() + xlab("Group") + ylab("PIQ") + ggtitle("PIQ per group") 
ggplot(demo,aes(Group,VIQ, color=Group)) + geom_boxplot() + geom_point() + theme_classic() + xlab("Group") + ylab("VIQ") + ggtitle("VIQ per group") 
ggplot(demo,aes(Group,FIQ, color=Group)) + geom_boxplot() + geom_point() + theme_classic() + xlab("Group") + ylab("FIQ") + ggtitle("FIQ per group") 
ggplot(demo,aes(Group,SP, color=Group)) + geom_boxplot() + geom_point() + theme_classic() + xlab("Group") + ylab("SP") + ggtitle("SP per group")
ggplot(demo,aes(Group,CBCL, color=Group)) + geom_boxplot() + geom_point() + theme_classic() + xlab("Group") + ylab("CBCL attention problems T-score") + ggtitle("CBCL attention problems T-score score per group")

ggboxplot(demo, x = "Group", y = "leeftijd", color = "Group", legend = "right", ylab="Age", xlab = "Group" ) 

```
#Correlation plots
```{r}
slopes_shift_demo<- inner_join(slopes_shift,demo, by='id')
ggplot(slopes_shift_demo, aes(SRS_TOTAAL,difference_slope)) + geom_point()
ggplot(slopes_shift_demo, aes(IU,difference_slope)) + geom_point()
ggplot(slopes_shift_demo, aes(IU,block_4)) + geom_point()
```

